version: 1

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html
  
python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
